# based on https://github.com/Arcnor/MiyooCFW/blob/ci/.github/workflows/main.yml
name: CI Build

on: [push, pull_request]

jobs:   
  build-gmenunx:
    runs-on: ubuntu-20.04
    container:
      # note: nfriedly/miyoo-toolchain:steward can also be used for an env compatible with miyoo 1.3.3
      image: nfriedly/miyoo-toolchain:musl
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: make -f Makefile.miyoo dist
    - uses: actions/upload-artifact@v2
      with:
        name: GMenuNX binary
        path: objs/miyoo/gmenu2x
        if-no-files-found: error # 'error', 'warn', 'ignore'; defaults to `warn`
    - uses: actions/upload-artifact@v2
      with:
        name: GMenuNX binary (debug)
        path: objs/miyoo/gmenu2x-debug
        if-no-files-found: error # 'error', 'warn', 'ignore'; defaults to `warn`
    - uses: actions/upload-artifact@v2
      with:
        name: GMenuNX Bundle
        path: dist/miyoo/GMenuNX.zip
        if-no-files-found: error # 'error', 'warn', 'ignore'; defaults to `warn`
