
name: CI Build

on: [push, pull_request]

jobs:   
  build-modern:
    name: GMenu2X for MiyooCFW (dynamic uClibc)
    runs-on: ubuntu-20.04
    container:
      image: nfriedly/miyoo-toolchain:steward
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: make -f Makefile.miyoo dist
    - uses: actions/upload-artifact@v3
      with:
        name: GMenu2X binary
        path: dist/miyoo/gmenu2x
        if-no-files-found: error # 'error', 'warn', 'ignore'; defaults to `warn`
    - uses: actions/upload-artifact@v3
      with:
        name: GMenu2X binary (debug)
        path: dist/miyoo/gmenu2x-debug
        if-no-files-found: error # 'error', 'warn', 'ignore'; defaults to `warn`
    - uses: actions/upload-artifact@v3
      with:
        name: GMenu2X Bundle 
        path: |
          dist/miyoo/
          !dist/miyoo/gmenu2x-debug
        if-no-files-found: error # 'error', 'warn', 'ignore'; defaults to `warn`
